spring:
  # ????????
  datasource:
    url: jdbc:mysql://localhost:3306/library_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root # <-- ????? MySQL ???
    password: Lv050611_ # <-- ????? MySQL ??
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/Hibernate (JPA???????????????)
  jpa:
    hibernate:
      ddl-auto: validate # ?????????????????????

# MyBatis ??
mybatis:
  # ?? MyBatis XML ???????
  mapper-locations: classpath:mapper/*.xml
  # ??????????????? XML ???
  type-aliases-package: com.chaos.schoollib.entity
  # ?? MyBatis ???????? SQL
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# ???????
server:
  port: 8888

# JWT ????
jwt:
  secret: "4JfTqMBa8cOyFfjCDzOGvQ13WC4v+Z2rmSVQlj1kAiM="
  expiration-ms: 86400000 # 24 hours (24 * 60 * 60 * 1000)